apiVersion: v1
kind: Pod
metadata:
  name: ehrbasedb
spec:
    containers:
    - name: ehrbasedb
      image: ehrbase/ehrbase-postgres:latest
      securityConext:
        privileged: true
      volumeMounts:
      - mountPath: /data
        name: hostpath-privileged
      ports:
      - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: EHRBASE_USER
          value: ehrbase
        - name: EHRBASE_PASSWORD
          value: ehrbase
    securityContext: {}
    volumes:
      - name: hostpath-privileged
        persistentVolumeClaim:
          claimName: /data

