apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehrbasedb-deployment
spec:
  selector:
    matchLabels:
      app: ehrbasedb
  replicas: 1
  template:
    metadata:
      labels:
        app: ehrbasedb
    spec:  
      containers:
      - name: ehrbasedb
        image: ehrbase/ehrbase-postgres:latest
        volumeMounts:
        - name: ehrbase-storage
          mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: ehrbase
          - name: POSTGRES_PASSWORD
            value: ehrbase
          - name: POSTGRES_db
            value: ehrbase
      volumes:
      - name: ehrbase-storage
        persistentVolumeClaim:
           claimName: ehrbase-storage

