apiVersion: v1
kind: Deployment
metadata:
  name: ehrbase-deployment
spec:
  selector:
    matchLabels:
      app: ehrbase
  replicas: 1
  template:
    metadata:
      labels:
        app: ehrbase
    spec:  
      containers:
      - name: ehrbase
        image: ehrbase/ehrbase:0.16.5
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_UR
            value: jdbc:postgresql://ehrbasedb:5432/ehrbase
          - name: SPRING_DATASOURCE_USERNAME
            value: ehrbase
          - name: SPRING_DATASOURCE_PASSWORD
            value: ehrbase
          - name: SERVER_AQLCONFIG_USEJSQUERY
            value: "false"
