apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehrbasedb-deployment
spec:
  selector:
    matchLabels:
      app: ehrbasedb
  replicas: 1
  template:
    metadata:
      labels:
        app: ehrbasedb
    spec:  
      containers:
      - name: ehrbasedb
        image: postgres
        securityContext:
          fsGroup: 1234
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
        env:
          - name: POSTGRES_USER
            value: ehrbase
          - name: POSTGRES_PASSWORD
            value: ehrbase
          - name: POSTGRES_db
            value: ehrbase
      volumes:
      - name: data
        hostPath:
          path: /root/EHRBase/.pgdata
