apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehrbasedb-deployment
data: 
  POSTGRES_DB: ehrbase
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
spec:
  selector:
    matchLabels:
      app: ehrbasedb
  replicas: 1
  template:
    metadata:
      labels:
        app: ehrbasedb
    spec:  
      containers:
      - name: pgdata
        image: agustinpallares/ehrbasedb
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: EHRBASE_USER
            value: ehrbase
          - name: EHRBASE_PASSWORD
            value: ehrbase
