apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:  
      containers:
      - name: postgres
        image: ehrbase/ehrbase-postgres:latest
        ports:
         - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: EHRBASE_USER
            value: ehrbase
          - name: EHRBASE_PASSWORD
            value: ehrbase
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
